services:
  - type: web
    name: taskpro
    plan: free
    region: singapore
    runtime: python
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn task_management.wsgi --bind 0.0.0.0:$PORT --workers 2 --log-file -"
    autoDeploy: true
    healthCheckPath: "/"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgres.cwrdmpbrqrekdyyembvu:w3Az8TyfXBm9dRth@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require"
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "event-management-website-1-0g6e.onrender.com,.onrender.com,localhost,127.0.0.1"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.10"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: WEB_CONCURRENCY
        value: "2"
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        value: "rifatrizviofficial001@gmail.com"
      - key: EMAIL_HOST_PASSWORD
        value: "piuy caic sdkc xmuv"
      - key: FRONTEND_URL
        value: "https://event-management-website-1-0g6e.onrender.com"