# Generated by Django 6.0 on 2026-02-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_remove_employee_user_alter_task_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskdetail",
            name="asset_caption",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="taskdetail",
            name="asset_image",
            field=models.ImageField(
                blank=True,
                default="task_assets/default_image.jpg",
                null=True,
                upload_to="task_assets/%Y/%m/%d/",
            ),
        ),
    ]
